version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: cimg/openjdk:17.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "code checked out"
